# Generated by Django 5.2.4 on 2025-08-04 13:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        error_messages={"min_value": "Year must be 2000 or later."},
                        help_text="Year of the investment, must be a positive integer",
                        validators=[django.core.validators.MinValueValidator(2000)],
                        verbose_name="Investment Year",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("First Half", "First Half"),
                            ("Third Quarter", "Third Quarter"),
                            ("Fourth Quarter", "Fourth Quarter"),
                        ],
                        help_text="Period of the investment (First Half, Third Quarter, Fourth Quarter)",
                        max_length=20,
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Unique code for the investment asset",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "ownership",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Ownership percentage of the investment, represented as a decimal",
                        max_digits=5,
                    ),
                ),
                (
                    "aquization_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the investment was acquired",
                        null=True,
                    ),
                ),
                (
                    "Ultimate_parent",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Ultimate parent company of the investment",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "RelationShip_of_investment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Subsidiary", "Subsidiary"),
                            ("Joint venture", "Joint venture"),
                            ("Associate", "Associate"),
                            ("Subsidiary of Associate", "Subsidiary of Associate"),
                            (
                                "Joint Venture of Associate",
                                "Joint Venture of Associate",
                            ),
                            ("Associate of Associate", "Associate of Associate"),
                            ("Subsidiary of a JV", "Subsidiary of a JV"),
                            ("Associate", "Associate"),
                            ("Subsidiary", "Subsidiary"),
                            ("Associate of a JV", "Associate of a JV"),
                            ("Joint Venture of a JV", "Joint Venture of a JV"),
                        ],
                        default=None,
                        help_text="Relationship of the investment to the parent company",
                        max_length=100,
                        null=True,
                        verbose_name="Relationship of Investment",
                    ),
                ),
                (
                    "direct",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Indicates if the investment is direct or indirect",
                        null=True,
                        verbose_name="Direct Investment",
                    ),
                ),
                (
                    "Entity_Principal_activities",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Principal activities of the investment entity",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Investment",
                "verbose_name_plural": "Investments",
                "db_table": "investments",
                "ordering": ["-year", "period"],
            },
        ),
    ]
