# Generated by Django 5.2.4 on 2025-08-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Investments", "0001_initial"),
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the investment record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_investments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="direct_parent",
            field=models.ForeignKey(
                help_text="Direct parent investment, if any",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investments_as_parent",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="entity",
            field=models.ForeignKey(
                help_text="Company associated with the investment",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="investments_as_entity",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who updated the investment record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_investments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
