# Generated by Django 5.2.5 on 2025-08-09 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('time_period', models.CharField(choices=[('First Half', 'First Half'), ('Third Quarter', 'Third Quarter'), ('Fourth Quarter', 'Fourth Quarter')], max_length=20)),
                ('dead_line', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('year', 'time_period')},
            },
        ),
    ]
