# Generated by Django 5.2.4 on 2025-08-03 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_company_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='arabic_name',
            field=models.CharField(blank=True, help_text='Arabic name of the company', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country_of_incorporation',
            field=models.CharField(blank=True, help_text='Country where the company is legally registered', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cr_number',
            field=models.CharField(blank=True, help_text='Commercial Registration Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='moi_number',
            field=models.CharField(blank=True, help_text='Ministry of Interior Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(help_text='Company this user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.company'),
        ),
    ]
