# Generated by Django 5.2.5 on 2025-08-09 15:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year of the investment, must be 2000 or later', validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Investment Year')),
                ('time_period', models.CharField(choices=[('First Half', 'First Half'), ('Third Quarter', 'Third Quarter'), ('Fourth Quarter', 'Fourth Quarter')], help_text='Time period of the investment', max_length=20)),
                ('asset_code', models.CharField(blank=True, help_text='Unique code for the investment asset', max_length=10, null=True)),
                ('entity_name', models.CharField(help_text='Name of the entity', max_length=255)),
                ('arabic_legal_name', models.CharField(blank=True, help_text='Arabic legal name of the entity', max_length=255, null=True)),
                ('commercial_registration_number', models.CharField(blank=True, help_text='Commercial Registration (CR) Number', max_length=50, null=True)),
                ('moi_number', models.CharField(blank=True, help_text='MOI (700) Number', max_length=50, null=True)),
                ('country_of_incorporation', models.CharField(blank=True, help_text='Country of Incorporation', max_length=100, null=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Ownership Percentage (%)', max_digits=5)),
                ('acquisition_disposal_date', models.DateField(blank=True, help_text='Acquisition/Disposal Date (only for entities acquired/disposed)', null=True)),
                ('direct_parent', models.CharField(blank=True, help_text='Direct Parent', max_length=255, null=True)),
                ('ultimate_parent', models.CharField(blank=True, help_text='Ultimate Parent', max_length=255, null=True)),
                ('relationship_of_investment', models.CharField(blank=True, choices=[('Subsidiary', 'Subsidiary'), ('Associate', 'Associate'), ('JV', 'Joint Venture')], help_text='Relationship of investment (Subsidiary / Associate / JV)', max_length=50, null=True)),
                ('direct_or_indirect', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], help_text='Direct or Indirect investment', max_length=10, null=True)),
                ('entities_principal_activities', models.CharField(blank=True, help_text="Entity's Principal Activities", max_length=255, null=True)),
                ('is_submitted', models.BooleanField(default=False, help_text='Indicates if the investment record is submitted')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when submitted', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this investment', on_delete=django.db.models.deletion.PROTECT, related_name='created_investments', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who submitted this investment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_investments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this investment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments',
                'ordering': ['-year', 'time_period'],
            },
        ),
    ]
